//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
namespace QuickMesh
{

		public class Feature
		{
			public static Vector3 DefaultOrientation = Vector3.left;	
			public static Vector3 DefaultDirection = Vector3.forward;
			public List<Face> Faces = new List<Face>();
			public Vector3 Direction = DefaultDirection;
			public Vector3 Orientation = DefaultOrientation;
		}
}

