//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace QuickMesh
{
		public class Vertex
		{
			public Vector3 Position;
			public Vertex(Vector3 position){
				Position = position;
			}
			public Vertex(float x, float y, float z){
				Position = new Vector3 (x, y, z);
			}
		}
}

